# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fixture.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.protobuf.Request" do
    optional :name, :string, 1
    optional :user, :message, 2, "google.protobuf.User"
  end
  add_message "google.protobuf.User" do
    optional :name, :string, 1
    optional :type, :enum, 2, "google.protobuf.User.UserType"
    repeated :posts, :message, 3, "google.protobuf.Post"
    map :map_field, :string, :string, 4
    optional :bytes_field, :bytes, 5
    optional :timestamp, :message, 6, "google.protobuf.Timestamp"
  end
  add_enum "google.protobuf.User.UserType" do
    value :UNSPECIFIED, 0
    value :ADMINISTRATOR, 1
  end
  add_message "google.protobuf.Post" do
    optional :text, :string, 1
  end
end

module Google
  module Protobuf
    Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.protobuf.Request").msgclass
    User = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.protobuf.User").msgclass
    User::UserType = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.protobuf.User.UserType").enummodule
    Post = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.protobuf.Post").msgclass
  end
end
